#  _                      _     _ _      
# | |__  _   _ _ __  _ __(_) __| | | ___ 
# | '_ \| | | | '_ \| '__| |/ _` | |/ _ \
# | | | | |_| | |_) | |  | | (_| | |  __/
# |_| |_|\__, | .__/|_|  |_|\__,_|_|\___|
#        |___/|_|                        


# Source the colors-hyprland file to load environment variables
source /home/$USER/.cache/wal/colors-hyprland

general {
    lock_cmd = pidof hyprlock || hyprlock
    ignore_dbus_inhibit = /opt/spotify/spotify
}

listener {
    timeout = 270
    on-timeout = source /home/eli/.cache/wal/colors.sh && notify-send "System" "You are about to be locked out!" -i $wallpaper
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
    on-resume = sleep 2 && source /home/eli/.cache/wal/colors.sh && notify-send "System" "Unlocked! Hey $USER" -i $wallpaper
}

listener {
    timeout = 1200
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

# Screenlock
listener {
    # HYPRLOCK TIMEOUT
    timeout = 600
    # HYPRLOCK ONTIMEOUT
    on-timeout = loginctl lock-session
}
