# -----------------------------------------------------
# Programs
# -----------------------------------------------------
$terminal = warp-terminal
$fileManager = dolphin
$menu = wofi --show drun

# -----------------------------------------------------
# Autostart
# -----------------------------------------------------

# Setup XDG for screen sharing
exec-once = ~/.config/hypr/scripts/xdg.sh

# Start Polkit
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Load Swaync Notification Manager
exec-once = swaync && swaync-client -df

# Using hypridle to start hyprlock
exec-once = hypridle

# Load Wallpaper System
exec-once = swww-daemon

# Load Waybar to navbarw
exec-once = waybar

# -------------------------------
# Load cliphist history
exec-once = wl-paste --watch cliphist store

# Start ewww daemon
exec-once = ags &

# Load GTK settings
exec-once = ~/.config/hypr/scripts/gtk.sh
