# -----------------------------------------------------
# General window layout and colors
# -----------------------------------------------------

# Colors
source = /home/caiop/.cache/wal/colors-hyprland.conf

# Configs
general {
    gaps_in = 6
    gaps_out = 14
    border_size = 0
    col.active_border = $color9
    col.inactive_border = rgba(00000000)
    resize_on_border = true
    layout = dwindle
}

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
